describe('Application Origin Flow', () => {
  beforeEach(() => {
    // Clear state before each test
    cy.window().then((win) => win.localStorage.clear());
    // Login as proponent
    cy.visit('/login');
    cy.get('input[type="email"]').type('proponent@example.com');
    cy.get('input[type="password"]').type('Proponent@1234');
    cy.get('button[type="submit"]').click();
    cy.url().should('include', '/dashboard/proponent');
  });

  it('should be able to create a new draft application', () => {
    // Navigate to new application form
    cy.contains('New Application').click();
    cy.url().should('include', '/dashboard/proponent/new');

    // Fill out the form
    const randomProjectName = `Test Project ${Date.now()}`;
    cy.get('input[placeholder="e.g. Raipur Steel Plant Expansion"]').type(randomProjectName);
    cy.get('select').first().select('Industry'); // Sector
    cy.get('select').last().select('Raipur'); // District
    
    cy.get('textarea[placeholder="Briefly describe the project…"]').type('This is an automated test project generated by Cypress.');
    
    cy.get('input[placeholder="e.g. 150.5"]').type('10.5'); // Area
    cy.get('input[placeholder="e.g. 250"]').type('50'); // Investment
    
    cy.contains('Next').click();
    cy.url().should('include', '/dashboard/proponent/new');
    
    // Move to next step (Documents)
    cy.contains('Next').click();
    
    // Verify toast for draft creation
    cy.contains('Draft saved!').should('be.visible');
    
    // Skip documents for now (Click Next)
    cy.contains('Next').click();
    
    // Skip Payment Info (Click Next)
    cy.contains('Next').click();
    
    // Final review step
    cy.contains(/Open Application|Save as Draft/i).click();
    
    // Assert redirect and success
    cy.url().should('include', '/dashboard/proponent/application/');
    
    // Verify it is in Draft status
    cy.contains('Draft').should('be.visible');
    cy.contains(randomProjectName).should('be.visible');
  });
});
